### ISSUE TITLE
Double clicking issue

### ISSUE THREAD

**Issue by LeonCheung** [chromoly/blender-ScreencastKeysMod#1]
Hi Chromoly,

First thanks a lot for continuous development on this mod version. It really helps. (And I'm the big fun of your classic Ruler addon. Just wonder why it currently drops so many features that was used to supported in Blender 2.5x age.... :\ )

While doubling clicking on keys quickly, for example, LMB or R, it will display LMB X3 or R x3 instead of x2. Is that possible to fix it? Thanks!

**Comment by chromoly** [comment]
可能なら修正してみます

**Comment by chromoly** [comment]
修正しました
